### PR TITLE
added ifconfig for network usage on motd

### PR DESCRIPTION
**Pull request by fernviridian**

### CODE REVIEW

**Comment by gagle** [comment]
Sorry, but I cannot add a new line. 5 is the maximum because the message must have a dimension of 80x24. The best solution is to maintain your fork as a separate project for the people that don't care about the 24 lines limit.

**Comment by fernviridian** [comment]
Is there something limiting the size to 80x24? Could one of the blank lines above the raspberry be removed to keep the format?

**Comment by gagle** [comment]
80x24 is the default size of a console window. Feel free to modify anything for your needs but the main repository doesn't accept new additions, just bugfixes, but I think that all is working fine.

**Comment by gagle** [comment]
Wait a sec, I can just replace the temperature label by the network stats. I think it's more interesting.

Edit: Feature discarded. `ifconfig` it's the most popular command... The submitted code is not working.

**Pull request closed without merging**
